### ISSUE TITLE
Get field helper method needed

### ISSUE THREAD

**Issue by rtpHarry** [cdillon/strong-testimonials#2]
The custom templates functionality is very handy but at the moment it is missing a way for you to pull a field into a variable so that you can make decisions based on it. As soon as you call `wpmtst_field( 'company_name')` it gets echoed straight out.

For my custom template I want a dash between the client name and company name but if there isnt a company name I dont want the dash, eg:

    // in the template:
    <?php echo format_attrib(wpmtst_field( 'client_name' ), wpmtst_field( 'company_name')); ?>

    // help function
	function format_attrib($client_name, $company_name) {
		$client_name = trim($client_name);
		$company_name = trim($company_name);

		if(($client_name !== '') && ($company_name !== '')) {
			return "<p class='attrib'><strong>" . $company_name . "</strong> - " . $client_name . "</p>";
		}

		if($client_name !== '') {
			return '<p class="attrib"><strong>' . $client_name . '</strong></p>';
		}

		if($company_name !== '') {
			return '<p class="attrib"><strong>' . $company_name . '</strong></p>';
		}

		return "";
	}

This doesn't work as the first line doesn't get the field returned, so we need something like:

    function wpmtst_getfield( $field = null, $args = array() ) {
        if ( ! $field ) return '';
            
        global $post;
        $html = '';
        
        switch( $field ) {
        
            // Apply a character limit to post content.
            case 'truncated' :
                $html = wpmtst_truncate( $post->post_content, $args['char_limit'] );
                break;
            
            // Process child shortcodes in [strong] content.
            case 'client' :
                $html = do_child_shortcode( 'strong', $args['content'] );
                break;
            
            // Get the custom field.
            default :
                $html = get_post_meta( $post->ID, $field, true );
                
        }
        return $html;
    }

**Comment by cdillon** [comment]
Thanks for pointing this out. I will include this or something similar in the next release.
