### ISSUE TITLE
Errors displayed when debug is turned on

### ISSUE THREAD

**Issue by rtpHarry** [cdillon/strong-testimonials#3]
I've updated to the latest version of Strong Testimonials (1.15.6) and I have the debug messages turned on while I'm developing a site it shows a lot of errors at the top of the site:

    Strict Standards: Only variables should be passed by reference in /srv/www/example/htdocs/wp-content/plugins/strong-testimonials/includes/class-strong-testimonials-plugin.php on line 436
    
    Notice: Undefined offset: 4 in /srv/www/example/htdocs/wp-content/plugins/strong-testimonials/includes/class-strong-testimonials-plugin.php on line 438
    
    Strict Standards: Only variables should be passed by reference in /srv/www/example/htdocs/wp-content/plugins/strong-testimonials/includes/class-strong-testimonials-plugin.php on line 436
    
    Strict Standards: Only variables should be passed by reference in /srv/www/example/htdocs/wp-content/plugins/strong-testimonials/includes/class-strong-testimonials-plugin.php on line 436
    
    Strict Standards: Only variables should be passed by reference in /srv/www/example/htdocs/wp-content/plugins/strong-testimonials/includes/class-strong-testimonials-plugin.php on line 436
    
    Strict Standards: Only variables should be passed by reference in /srv/www/example/htdocs/wp-content/plugins/strong-testimonials/includes/class-strong-testimonials-plugin.php on line 436
    
    Strict Standards: Only variables should be passed by reference in /srv/www/example/htdocs/wp-content/plugins/strong-testimonials/includes/class-strong-testimonials-plugin.php on line 436

It seems that you can solve the Strict Standards issue by using an @ according to this:

  - http://stackoverflow.com/questions/2354609/strict-standards-only-variables-should-be-passed-by-reference

But I'm still seeing the `undefined offset` issue still.

**Comment by cdillon** [comment]
Thanks for catching this. I fixed it in 1.15.7. And I added wpmtst_get_field() to return the HTML of a custom field per your previous request.
