### ISSUE TITLE
Template discoverability

### ISSUE THREAD

**Issue by rtpHarry** [cdillon/strong-testimonials#4]
I was thinking about these templates this morning and thought I would open a discussion up here to see what your thinking is.

As I've gone along I've built up several different templates that I would like to able to add in to projects easily. I'm also thinking about distributing some templates as a free download for users but would like the process to be as frictionless as possible.

At the moment the templates have to be placed in a certain folder in the theme in order for it to be discoverable. I'm just an intermediate developer at the moment so not sure about all the ins and outs of WP development but I think this means I can't distribute them wrapped up in a plugin without having the plugin write the files to the template root which could cause permissions issues for the end-user.

I thought maybe you could register the templates using an action/filter (haven't looked up which is appropriate yet) rather than locking them to a certain location? I guess if you did do this then you could also provide a mechanism to enqueue scripts / styles along with the templates?

I've seen in your readme's that you're aware this is an area for improvement with the plugin so just thought I would pick your brains on the direction you see it going in. :)

**Comment by cdillon** [comment]
The next two features are Views and Templates. I plan to build various templates too, though I plan to sell them in an add-on. (Let me know if you would like to participate.)

> At the moment the templates have to be placed in a certain folder in the theme in order for it to be discoverable.

I have been placing custom templates in the theme's top directory. I have not tried subdirectories. Are you having problems with this?

You are correct in saying that having a plugin write files to the theme would be problematic. Plus, changing the theme would orphan your custom templates. Sure, if someone created their own custom template and changed their theme, the burden is on them to copy their template over.

The WP template hierarchy does not have a mechanism for searching in a plugin, except for hooking into the `{$type}_template` filter at the end of its search within the theme. I'm not aware of a way to register templates as we do with styles and scripts but we are not alone in wishing this feature existed.

The plugin now returns the default template from the plugin template directory. The plan is to mimic the theme `locate_template` discovery process as much as needed on the plugin side. Adding a new template will be as simple as creating a new subdirectory. This directory-based discovery method will serve as our process for registering templates and enqueueing distinct styles and scripts.

I plan to keep it simple. I consider a group of templates (page, widget, form) as a mini-theme; perhaps "layout" is a better word. For example, if a plugin template layout is named "Rounded Blue" in the "templates/rounded-blue" subdirectory, the main template file will be "testimonials-page.php" and its accordant stylesheet must be named "testimonials-page.css". 

However, that tight coupling does not allow file-based variations within the same layout; i.e. attaching a different stylesheet like "light-blue.css". That would require a separate registration process, UI, and storing the assignment in the database. That is doable with the View component I'm working on but let's see how this directory-based approach works first. So variations will need to be handled via classes like ".light-blue" within the template stylesheet and selecting that class via shortcode attribute or View setting.

I have not examined other plugins that offer templates to know if there's a single best way to do this, and I like to stand on the shoulders of giants where possible, but my hunch is they take a similar approach though perhaps more refined and robust.

**Comment by cdillon** [comment]
@rtpHarry, I don't know if you're still using the plugin but I have some news.

Version 1.25 (six weeks in the making) now offers a better process for locating templates. I will publish a full tutorial soon on wpmission.com. 

The default group is in /templates/default. Three types are recognized: content.php, widget.php, and form.php. Each can have a single stylesheet and the basename must match; e.g. content.css.

To create a custom template, create a subdirectory named /strong-testimonials in your theme and then create a group subdirectory(ies) under that; e.g. /default, /custom, /my-blue-template, etc.

The group name will be used in the template list in the View editor. "Display" and "Slideshow" modes will build a list of content and widget templates, and "Form" mode will build a list of only form templates.

There is also a filter for modifying the search path.
