### ISSUE TITLE
translation does not work

### ISSUE THREAD

**Issue by meberli** [cdillon/strong-testimonials#8]
translations for the frontend form are not applied.  
only english texts are shown - regardless of the current language, 
I tried it with french and spanish

steps to reproduce:
- create view form
- add this view it to a page ([testimonial_view id=1])
- change language to spanish in wp settings

**Comment by cdillon** [comment]
Since the front-end form texts are dynamic, they are not available when the po/mo files are created. They must be translated using the String Translation feature of the WPML or Polylang plugins.

**Comment by meberli** [comment]
I do not use WPML or Polylang. The site is entirely in german.
I just started work for a german translation of strong-testimonials.
